export type CategoryId = 'men' | 'women' | 'kids';

export interface Product {
  id: string;
  name: string;
  category: CategoryId;
  type: string;
  price: string;
  priceNum: number;
  image: string;
  gallery: string[];
  status?: 'NEW ARRIVAL' | 'SOLD OUT';
  colors: { id: string; hex: string; name: string }[];
  sizes: string[];
  description: string;
  fabric: string;
  fit: string;
  rating: number;
  reviewCount: number;
}

export const PRODUCTS: Product[] = [
  // ==========================================
  // MEN'S COLLECTION (18 Products)
  // ==========================================
  {
    id: 'm-01',
    name: 'Heavyweight Boxy Tee',
    category: 'men',
    type: 'T-Shirts',
    price: '$95.00',
    priceNum: 95,
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1000&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=1000&auto=format&fit=crop',
    ],
    status: 'NEW ARRIVAL',
    colors: [
      { id: 'black', hex: '#000000', name: 'Onyx Black' },
      { id: 'white', hex: '#FFFFFF', name: 'Chalk White' },
      { id: 'slate', hex: '#4B5563', name: 'Mineral Slate' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Engineered in custom 320 GSM long-staple combed cotton jersey with dropped shoulder seams and reinforced ribbed collar.',
    fabric: '100% Combed Heavyweight Cotton (320 GSM). Pre-shrunk with enzyme wash.',
    fit: 'Oversized boxy silhouette.',
    rating: 4.9,
    reviewCount: 142,
  },
  {
    id: 'm-02',
    name: 'Pleated Wool Wide Trousers',
    category: 'men',
    type: 'Trousers',
    price: '$280.00',
    priceNum: 280,
    image: 'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?q=80&w=1000&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?q=80&w=1000&auto=format&fit=crop',
    ],
    colors: [
      { id: 'black', hex: '#000000', name: 'Pitch Black' },
      { id: 'charcoal', hex: '#1F2937', name: 'Deep Charcoal' },
      { id: 'chalk', hex: '#E5E7EB', name: 'Off-White Wool' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Tailored from high-twist tropical virgin wool with double forward pleats and concealed waistband tab closures.',
    fabric: '100% Virgin Tropical Wool with cupro half-lining.',
    fit: 'High-rise with a generous straight-wide leg break.',
    rating: 4.8,
    reviewCount: 96,
  },
  {
    id: 'm-03',
    name: 'Architectural Trench Coat',
    category: 'men',
    type: 'Outerwear',
    price: '$620.00',
    priceNum: 620,
    image: 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?q=80&w=1000&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1544022613-e87ce7526edb?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1520975954732-35dd22299614?q=80&w=1000&auto=format&fit=crop',
    ],
    status: 'NEW ARRIVAL',
    colors: [
      { id: 'black', hex: '#000000', name: 'Caviar' },
      { id: 'chalk', hex: '#E5E7EB', name: 'Raw Twill' },
    ],
    sizes: ['S', 'M', 'L'],
    description: 'Built from bonded water-repellent gabardine twill with inverted storm gusset and matte metal D-ring belt hardware.',
    fabric: 'Bonded Cotton Twill with fluorocarbon-free water-resistant coating.',
    fit: 'Cocoon drape with raglan shoulders designed for winter layering.',
    rating: 5.0,
    reviewCount: 54,
  },
  {
    id: 'm-04',
    name: 'Minimalist Zip Blouson',
    category: 'men',
    type: 'Outerwear',
    price: '$390.00',
    priceNum: 390,
    image: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?q=80&w=1000&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1548883354-7622d03aca27?q=80&w=1000&auto=format&fit=crop',
    ],
    colors: [
      { id: 'black', hex: '#000000', name: 'Black' },
      { id: 'slate', hex: '#4B5563', name: 'Graphite' },
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    description: 'Utilitarian jacket tailored in dense technical matte poplin with a two-way brushed silver RiRi zipper.',
    fabric: 'High-density matte nylon-cotton blend lined in silk-touch cupro.',
    fit: 'Boxy cropped torso with elongated sleeves.',
    rating: 4.8,
    reviewCount: 78,
  },
  {
    id: 'm-05',
    name: 'Raw Edge Structured Blazer',
    category: 'men',
    type: 'Outerwear',
    price: '$480.00',
    priceNum: 480,
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1000&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?q=80&w=1000&auto=format&fit=crop',
    ],
    status: 'SOLD OUT',
    colors: [{ id: 'black', hex: '#000000', name: 'Raw Black' }],
    sizes: ['M', 'L'],
    description: 'Deconstructed tailored blazer with exposed raw selvedge perimeter details and sculpted peak lapels.',
    fabric: '100% Japanese Wool Gabardine.',
    fit: 'Relaxed structure with soft canvassed roped shoulders.',
    rating: 4.7,
    reviewCount: 31,
  },
  {
    id: 'm-06',
    name: 'French Terry Oversized Hoodie',
    category: 'men',
    type: 'Tops',
    price: '$210.00',
    priceNum: 210,
    image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=1000&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?q=80&w=1000&auto=format&fit=crop',
    ],
    colors: [
      { id: 'slate', hex: '#4B5563', name: 'Heather Slate' },
      { id: 'black', hex: '#000000', name: 'Washed Black' },
      { id: 'chalk', hex: '#E5E7EB', name: 'Oatmeal' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Loopback 480 GSM French terry hoodie with seamless kangaroo pocket and double-layered structured hood.',
    fabric: '100% Organic Heavy Cotton French Terry (480 GSM).',
    fit: 'Slouched dropped shoulders and cropped body hem.',
    rating: 4.9,
    reviewCount: 184,
  },
  {
    id: 'm-07',
    name: 'Technical Modular Cargo Pant',
    category: 'men',
    type: 'Trousers',
    price: '$310.00',
    priceNum: 310,
    image: 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'black', hex: '#000000', name: 'Tactical Black' },
      { id: 'charcoal', hex: '#1F2937', name: 'Graphite' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Crafted in weather-resistant ripstop nylon with magnetic bellows pockets and adjustable cinch ankles.',
    fabric: 'Cordura Ripstop with DWR finish.',
    fit: 'Articulated knee tailoring with relaxed taper.',
    rating: 4.9,
    reviewCount: 65,
  },
  {
    id: 'm-08',
    name: 'Washed Leather Moto Blouson',
    category: 'men',
    type: 'Outerwear',
    price: '$790.00',
    priceNum: 790,
    image: 'https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1512436991641-6745cdb1723f?q=80&w=1000&auto=format&fit=crop'],
    status: 'NEW ARRIVAL',
    colors: [{ id: 'black', hex: '#000000', name: 'Vintage Black' }],
    sizes: ['M', 'L', 'XL'],
    description: 'Full-grain lambskin leather drum-dyed and tumbled for a vintage drape, finished with brushed silver hardware.',
    fabric: '100% Genuine Lambskin Leather, Cupro Lining.',
    fit: 'Boxy motorcycle silhouette.',
    rating: 5.0,
    reviewCount: 42,
  },
  {
    id: 'm-09',
    name: 'Relaxed Fine Merino Crewneck',
    category: 'men',
    type: 'Tops',
    price: '$240.00',
    priceNum: 240,
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1620799139507-2a76f79a2f4d?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'charcoal', hex: '#1F2937', name: 'Charcoal' },
      { id: 'chalk', hex: '#E5E7EB', name: 'Raw Sand' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Knitted from ultrafine 19.5-micron Australian merino wool with saddle shoulder construction.',
    fabric: '100% Extra Fine Merino Wool.',
    fit: 'Fluid relaxed drape.',
    rating: 4.8,
    reviewCount: 88,
  },
  {
    id: 'm-10',
    name: 'Oversized Poplin Studio Shirt',
    category: 'men',
    type: 'Tops',
    price: '$180.00',
    priceNum: 180,
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'white', hex: '#FFFFFF', name: 'Optical White' },
      { id: 'slate', hex: '#4B5563', name: 'Steel Blue' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Tailored in crisp 120s two-ply organic cotton poplin with exaggerated barrel cuffs and curved hem.',
    fabric: '100% GOTS Certified Organic Cotton Poplin.',
    fit: 'Voluminous studio cut.',
    rating: 4.7,
    reviewCount: 52,
  },
  {
    id: 'm-11',
    name: 'Selvedge Wide Denim Jean',
    category: 'men',
    type: 'Trousers',
    price: '$260.00',
    priceNum: 260,
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1582552938357-32b906df40cb?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'slate', hex: '#4B5563', name: 'Vintage Indigo' },
      { id: 'black', hex: '#000000', name: 'Washed Black' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    description: '14oz shuttle-loom Japanese selvedge denim, rinsed once with natural indigo warp and unbleached ecru weft.',
    fabric: '100% Cotton 14oz Japanese Selvedge Denim.',
    fit: 'Mid-rise with wide straight leg.',
    rating: 4.9,
    reviewCount: 110,
  },
  {
    id: 'm-12',
    name: 'Heavy Rib Mockneck Long Sleeve',
    category: 'men',
    type: 'T-Shirts',
    price: '$120.00',
    priceNum: 120,
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'black', hex: '#000000', name: 'Pitch Black' },
      { id: 'white', hex: '#FFFFFF', name: 'Chalk' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Custom heavyweight 1x1 rib knit with a 2-inch standing collar and clean seamless wrists.',
    fabric: '95% Combed Cotton, 5% Elastane.',
    fit: 'Slim athletic architectural profile.',
    rating: 4.8,
    reviewCount: 74,
  },
  {
    id: 'm-13',
    name: 'Double-Breasted Wool Overcoat',
    category: 'men',
    type: 'Outerwear',
    price: '$680.00',
    priceNum: 680,
    image: 'https://images.unsplash.com/photo-1544022613-e87ce7526edb?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1516257984-b1b4d707412e?q=80&w=1000&auto=format&fit=crop'],
    status: 'NEW ARRIVAL',
    colors: [
      { id: 'black', hex: '#000000', name: 'Midnight' },
      { id: 'charcoal', hex: '#1F2937', name: 'Espresso' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Tailored from heavyweight double-faced melton wool with broad peak lapels and horn buttons.',
    fabric: '80% Recycled Melton Wool, 20% Cashmere.',
    fit: 'Sculptural long silhouette with structured shoulders.',
    rating: 5.0,
    reviewCount: 39,
  },
  {
    id: 'm-14',
    name: 'Washed Silk Camp Collar Shirt',
    category: 'men',
    type: 'Tops',
    price: '$230.00',
    priceNum: 230,
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'black', hex: '#000000', name: 'Black Sand' },
      { id: 'chalk', hex: '#E5E7EB', name: 'Bone' },
    ],
    sizes: ['S', 'M', 'L'],
    description: 'Cut from sandwashed mulberry silk twill with straight hem and mother-of-pearl buttons.',
    fabric: '100% Mulberry Silk Twill (19mm).',
    fit: 'Relaxed resort drape.',
    rating: 4.8,
    reviewCount: 45,
  },
  {
    id: 'm-15',
    name: 'Pleated Linen Summer Trouser',
    category: 'men',
    type: 'Trousers',
    price: '$220.00',
    priceNum: 220,
    image: 'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'chalk', hex: '#E5E7EB', name: 'Natural Ecru' },
      { id: 'charcoal', hex: '#1F2937', name: 'Olive Drab' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Woven in Normandy linen with natural slub texture and double forward pleats.',
    fabric: '100% French Normandy Linen.',
    fit: 'Relaxed straight drape with extended tab waistband.',
    rating: 4.7,
    reviewCount: 62,
  },
  {
    id: 'm-16',
    name: 'Waffle Thermal Knit Henley',
    category: 'men',
    type: 'T-Shirts',
    price: '$110.00',
    priceNum: 110,
    image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'slate', hex: '#4B5563', name: 'Washed Slate' },
      { id: 'white', hex: '#FFFFFF', name: 'Chalk White' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Textured chunky waffle stitch in combed cotton with metal button placket.',
    fabric: '100% Combed Cotton Waffle Knit (350 GSM).',
    fit: 'Standard tailored fit.',
    rating: 4.8,
    reviewCount: 91,
  },
  {
    id: 'm-17',
    name: 'Puffer Down Quilted Vest',
    category: 'men',
    type: 'Outerwear',
    price: '$340.00',
    priceNum: 340,
    image: 'https://images.unsplash.com/photo-1548883354-7622d03aca27?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'black', hex: '#000000', name: 'Jet Black' },
      { id: 'slate', hex: '#4B5563', name: 'Gunmetal' },
    ],
    sizes: ['M', 'L', 'XL'],
    description: 'Filled with 750 fill-power responsibly sourced down with water-repellent shell and fleece collar.',
    fabric: 'Micro-Ripstop Nylon, 90/10 White Goose Down.',
    fit: 'Slightly cropped athletic layer.',
    rating: 4.9,
    reviewCount: 57,
  },
  {
    id: 'm-18',
    name: 'Raw Cotton Utility Overshirt',
    category: 'men',
    type: 'Tops',
    price: '$195.00',
    priceNum: 195,
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'charcoal', hex: '#1F2937', name: 'Charcoal Twill' },
      { id: 'chalk', hex: '#E5E7EB', name: 'Ecru Drill' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Heavy 11oz broken twill cotton jacket with oversized chest pockets and reinforced elbow patches.',
    fabric: '100% Unbleached Heavy Broken Twill Cotton.',
    fit: 'Square boxy overshirt cut.',
    rating: 4.8,
    reviewCount: 83,
  },

  // ==========================================
  // WOMEN'S COLLECTION (18 Products)
  // ==========================================
  {
    id: 'w-01',
    name: 'Sculptural Column Dress',
    category: 'women',
    type: 'Dresses',
    price: '$420.00',
    priceNum: 420,
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1000&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000&auto=format&fit=crop',
    ],
    status: 'NEW ARRIVAL',
    colors: [
      { id: 'black', hex: '#000000', name: 'Pitch Black' },
      { id: 'chalk', hex: '#E5E7EB', name: 'Bone Silk' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'Minimalist maxi dress crafted from double-faced silk crepe with a fluid high neckline and back slit.',
    fabric: '100% Heavy Silk Crepe de Chine with bonded hemline.',
    fit: 'Elongated body-skimming column silhouette.',
    rating: 5.0,
    reviewCount: 72,
  },
  {
    id: 'w-02',
    name: 'Oversized Cocoon Coat',
    category: 'women',
    type: 'Outerwear',
    price: '$580.00',
    priceNum: 580,
    image: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop',
    ],
    colors: [
      { id: 'charcoal', hex: '#1F2937', name: 'Charcoal Melange' },
      { id: 'chalk', hex: '#E5E7EB', name: 'Ecru Wool' },
    ],
    sizes: ['XS', 'S', 'M'],
    description: 'Sculptural dropped-shoulder cocoon coat woven in virgin brushed wool with deep concealed side pockets.',
    fabric: '90% Virgin Brushed Wool, 10% Cashmere.',
    fit: 'Dramatic rounded cocoon volume.',
    rating: 4.9,
    reviewCount: 88,
  },
  {
    id: 'w-03',
    name: 'Minimalist Poplin Shirt',
    category: 'women',
    type: 'Tops',
    price: '$190.00',
    priceNum: 190,
    image: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?q=80&w=1000&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?q=80&w=1000&auto=format&fit=crop',
    ],
    colors: [
      { id: 'white', hex: '#FFFFFF', name: 'Chalk White' },
      { id: 'slate', hex: '#4B5563', name: 'Faded Slate' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'Crisp high-thread-count cotton poplin button-down with pointed spread collar and wide cuffs.',
    fabric: '100% Giza Long-Staple Cotton Poplin.',
    fit: 'Generous architectural boyfriend drape.',
    rating: 4.8,
    reviewCount: 64,
  },
  {
    id: 'w-04',
    name: 'Tailored Pleated Trousers',
    category: 'women',
    type: 'Trousers',
    price: '$290.00',
    priceNum: 290,
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop',
    ],
    colors: [
      { id: 'black', hex: '#000000', name: 'Caviar' },
      { id: 'charcoal', hex: '#1F2937', name: 'Graphite' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'High-waisted wide trousers cut in structured wool-viscose with knife pleats and clean waistband.',
    fabric: '68% Virgin Wool, 30% Viscose, 2% Elastane.',
    fit: 'High-rise cinched waist falling into wide leg silhouette.',
    rating: 4.9,
    reviewCount: 112,
  },
  {
    id: 'w-05',
    name: 'Asymmetric Cashmere Knit',
    category: 'women',
    type: 'Tops',
    price: '$340.00',
    priceNum: 340,
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1000&auto=format&fit=crop',
    ],
    status: 'SOLD OUT',
    colors: [
      { id: 'black', hex: '#000000', name: 'Onyx' },
      { id: 'chalk', hex: '#E5E7EB', name: 'Oatmeal' },
    ],
    sizes: ['XS', 'S', 'M'],
    description: 'Spun from Mongolian grade-A cashmere with dramatic diagonal neckline drape and ribbed hem.',
    fabric: '100% Grade-A Mongolian Cashmere (7-gauge).',
    fit: 'Fluid relaxed body with fitted sleeves.',
    rating: 5.0,
    reviewCount: 94,
  },
  {
    id: 'w-06',
    name: 'Heavy Cotton Rib Tank',
    category: 'women',
    type: 'T-Shirts',
    price: '$85.00',
    priceNum: 85,
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=1000&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1000&auto=format&fit=crop',
    ],
    colors: [
      { id: 'white', hex: '#FFFFFF', name: 'Optic White' },
      { id: 'black', hex: '#000000', name: 'Black' },
      { id: 'gray', hex: '#9CA3AF', name: 'Heather Gray' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'Ultra-dense 2x2 ribbed cotton tank designed with high cut neckline and sculpted armholes.',
    fabric: '100% Supima Combed Cotton (280 GSM).',
    fit: 'Snug supportive architectural contour.',
    rating: 4.8,
    reviewCount: 168,
  },
  {
    id: 'w-07',
    name: 'Fluid Silk Bias-Cut Slip Dress',
    category: 'women',
    type: 'Dresses',
    price: '$380.00',
    priceNum: 380,
    image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'black', hex: '#000000', name: 'Midnight' },
      { id: 'chalk', hex: '#E5E7EB', name: 'Champagne' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'Cut entirely on the bias in heavy 22mm silk charmeuse that skims curves with effortless liquid grace.',
    fabric: '100% Heavy Mulberry Silk Charmeuse.',
    fit: 'Bias-cut drape with adjustable delicate straps.',
    rating: 4.9,
    reviewCount: 56,
  },
  {
    id: 'w-08',
    name: 'Double-Breasted Hourglass Blazer',
    category: 'women',
    type: 'Outerwear',
    price: '$520.00',
    priceNum: 520,
    image: 'https://images.unsplash.com/photo-1584273143981-41c073dfe8f8?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000&auto=format&fit=crop'],
    status: 'NEW ARRIVAL',
    colors: [
      { id: 'black', hex: '#000000', name: 'Obsidian' },
      { id: 'charcoal', hex: '#1F2937', name: 'Dark Taupe' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'Tailored with sharp shoulder pads and an intentional nipped waist for a powerful feminine silhouette.',
    fabric: '100% Virgin Wool with satin twill lining.',
    fit: 'Hourglass tailored silhouette.',
    rating: 5.0,
    reviewCount: 47,
  },
  {
    id: 'w-09',
    name: 'Wide-Leg Pleated Silk Pants',
    category: 'women',
    type: 'Trousers',
    price: '$310.00',
    priceNum: 310,
    image: 'https://images.unsplash.com/photo-1551803091-e20673f15770?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'black', hex: '#000000', name: 'Jet' },
      { id: 'chalk', hex: '#E5E7EB', name: 'Ivory' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'Heavy silk-wool blend trouser with dramatic double front pleats and fluid floor-sweeping hems.',
    fabric: '60% Silk, 40% Virgin Wool.',
    fit: 'High-waisted wide leg.',
    rating: 4.8,
    reviewCount: 79,
  },
  {
    id: 'w-10',
    name: 'Merino Wool Cardigan Coat',
    category: 'women',
    type: 'Tops',
    price: '$360.00',
    priceNum: 360,
    image: 'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'charcoal', hex: '#1F2937', name: 'Slate Gray' },
      { id: 'chalk', hex: '#E5E7EB', name: 'Sand Ecru' },
    ],
    sizes: ['XS', 'S', 'M'],
    description: 'Dense Milanese knit cardigan designed with clean shawl collar and waist tie belt.',
    fabric: '100% Extrafine Merino Wool (12-gauge).',
    fit: 'Elongated belted cardigan.',
    rating: 4.9,
    reviewCount: 63,
  },
  {
    id: 'w-11',
    name: 'Cutout Draped Halter Gown',
    category: 'women',
    type: 'Dresses',
    price: '$540.00',
    priceNum: 540,
    image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1000&auto=format&fit=crop'],
    status: 'NEW ARRIVAL',
    colors: [{ id: 'black', hex: '#000000', name: 'Nocturne Black' }],
    sizes: ['XS', 'S', 'M'],
    description: 'Haute couture halter gown featuring keyhole back cutout and twisted front drape in stretch crepe.',
    fabric: 'Heavy Rayon Crepe with elastane bounce.',
    fit: 'Floor-length sheath fit.',
    rating: 5.0,
    reviewCount: 38,
  },
  {
    id: 'w-12',
    name: 'Cropped Sculptural Trench Jacket',
    category: 'women',
    type: 'Outerwear',
    price: '$440.00',
    priceNum: 440,
    image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'chalk', hex: '#E5E7EB', name: 'Khaki Twill' },
      { id: 'black', hex: '#000000', name: 'Dark Ink' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'Deconstructed cropped trench featuring storm flap detailing and tortoiseshell button tabs.',
    fabric: '100% Water-Resistant Cotton Gabardine.',
    fit: 'Boxy cropped torso with wide sleeves.',
    rating: 4.8,
    reviewCount: 51,
  },
  {
    id: 'w-13',
    name: 'Draped Cashmere Turtleneck',
    category: 'women',
    type: 'Tops',
    price: '$295.00',
    priceNum: 295,
    image: 'https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'charcoal', hex: '#1F2937', name: 'Heather Smoke' },
      { id: 'chalk', hex: '#E5E7EB', name: 'Vanilla' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'Slouchy fold-over cowl turtleneck in brushed cashmere-silk blend with seamless ribbed trims.',
    fabric: '70% Cashmere, 30% Silk.',
    fit: 'Relaxed draped fit.',
    rating: 4.9,
    reviewCount: 92,
  },
  {
    id: 'w-14',
    name: 'Pleated Crepe Midi Skirt',
    category: 'women',
    type: 'Trousers',
    price: '$260.00',
    priceNum: 260,
    image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'black', hex: '#000000', name: 'Noir' },
      { id: 'slate', hex: '#4B5563', name: 'Steel Blue' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'Sunburst accordion pleating in fluid matte crepe that shifts gracefully with every movement.',
    fabric: '100% Recycled Polyester Crepe.',
    fit: 'High-waist A-line calf length.',
    rating: 4.7,
    reviewCount: 44,
  },
  {
    id: 'w-15',
    name: 'Oversized Silk Poplin Tunic',
    category: 'women',
    type: 'Tops',
    price: '$210.00',
    priceNum: 210,
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1434389677669-e08b4cac3105?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'white', hex: '#FFFFFF', name: 'Pure White' },
      { id: 'black', hex: '#000000', name: 'Caviar' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'Mandarin collar elongated tunic shirt with concealed button placket and side vents.',
    fabric: '70% Cotton, 30% Mulberry Silk.',
    fit: 'Oversized tunic length.',
    rating: 4.8,
    reviewCount: 71,
  },
  {
    id: 'w-16',
    name: 'High-Rise Sculpted Flare Jean',
    category: 'women',
    type: 'Trousers',
    price: '$240.00',
    priceNum: 240,
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'slate', hex: '#4B5563', name: 'Vintage Wash' },
      { id: 'black', hex: '#000000', name: 'Raw Black' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'Structured 12oz denim cut high on the waist with a subtle leg-lengthening flare from the knee down.',
    fabric: '98% Cotton, 2% Comfort Elastane.',
    fit: 'High-rise contoured flare.',
    rating: 4.9,
    reviewCount: 104,
  },
  {
    id: 'w-17',
    name: 'Boxy Heavyweight Crop Tee',
    category: 'women',
    type: 'T-Shirts',
    price: '$80.00',
    priceNum: 80,
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'white', hex: '#FFFFFF', name: 'Chalk White' },
      { id: 'black', hex: '#000000', name: 'Pitch Black' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'Dense organic cotton jersey cut with wide boxy shoulders and intentional clean crop.',
    fabric: '100% Organic Heavy Cotton (300 GSM).',
    fit: 'Boxy crop hitting at natural waistline.',
    rating: 4.8,
    reviewCount: 128,
  },
  {
    id: 'w-18',
    name: 'Reversible Shearling Aviator',
    category: 'women',
    type: 'Outerwear',
    price: '$890.00',
    priceNum: 890,
    image: 'https://images.unsplash.com/photo-1544022613-e87ce7526edb?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000&auto=format&fit=crop'],
    status: 'NEW ARRIVAL',
    colors: [
      { id: 'charcoal', hex: '#1F2937', name: 'Dark Mocha' },
      { id: 'chalk', hex: '#E5E7EB', name: 'Cream Shearling' },
    ],
    sizes: ['XS', 'S', 'M'],
    description: 'Spanish merino shearling jacket crafted with dual leather buckle throat latch and hand-waxed finish.',
    fabric: '100% Spanish Merino Lamb Shearling.',
    fit: 'Slightly oversized aviator jacket.',
    rating: 5.0,
    reviewCount: 33,
  },

  // ==========================================
  // KIDS' COLLECTION (18 Products)
  // ==========================================
  {
    id: 'k-01',
    name: 'Miniature Boxy Crewneck',
    category: 'kids',
    type: 'T-Shirts',
    price: '$65.00',
    priceNum: 65,
    image: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?q=80&w=1000&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?q=80&w=1000&auto=format&fit=crop',
    ],
    status: 'NEW ARRIVAL',
    colors: [
      { id: 'white', hex: '#FFFFFF', name: 'Chalk White' },
      { id: 'slate', hex: '#4B5563', name: 'Slate Blue' },
      { id: 'black', hex: '#000000', name: 'Jet Black' },
    ],
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    description: 'Proportionally scaled boxy tee in ultra-gentle long-staple organic cotton jersey.',
    fabric: '100% Organic Pima Cotton (240 GSM). Hypoallergenic enzyme wash.',
    fit: 'Relaxed mini-streetwear fit.',
    rating: 4.9,
    reviewCount: 68,
  },
  {
    id: 'k-02',
    name: 'Heavy Fleece Relaxed Sweatpant',
    category: 'kids',
    type: 'Trousers',
    price: '$85.00',
    priceNum: 85,
    image: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?q=80&w=1000&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?q=80&w=1000&auto=format&fit=crop',
    ],
    colors: [
      { id: 'charcoal', hex: '#1F2937', name: 'Heather Charcoal' },
      { id: 'chalk', hex: '#E5E7EB', name: 'Natural Ecru' },
    ],
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    description: 'Plush fleece sweatpants with elasticated pull-on waistband and reinforced interior knee seams.',
    fabric: '100% Brushed Organic Cotton Fleece (380 GSM).',
    fit: 'Comfortable relaxed leg with ribbed ankle cuff.',
    rating: 4.9,
    reviewCount: 52,
  },
  {
    id: 'k-03',
    name: 'Utility Canvas Chore Jacket',
    category: 'kids',
    type: 'Outerwear',
    price: '$140.00',
    priceNum: 140,
    image: 'https://images.unsplash.com/photo-1471286174890-9c112ffca56a?q=80&w=1000&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?q=80&w=1000&auto=format&fit=crop',
    ],
    status: 'NEW ARRIVAL',
    colors: [
      { id: 'charcoal', hex: '#1F2937', name: 'Washed Charcoal' },
      { id: 'chalk', hex: '#E5E7EB', name: 'Raw Twill' },
    ],
    sizes: ['6Y', '8Y', '10Y', '12Y'],
    description: 'Durable heavyweight cotton duck canvas jacket with front patch pockets and contrast corduroy collar.',
    fabric: '100% Heavy Cotton Duck Canvas with corduroy collar.',
    fit: 'Boxy heritage chore silhouette.',
    rating: 5.0,
    reviewCount: 41,
  },
  {
    id: 'k-04',
    name: 'Oversized Minimalist Hoodie',
    category: 'kids',
    type: 'Tops',
    price: '$95.00',
    priceNum: 95,
    image: 'https://images.unsplash.com/photo-1514090458221-65bb69cf63e6?q=80&w=1000&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?q=80&w=1000&auto=format&fit=crop',
    ],
    colors: [
      { id: 'black', hex: '#000000', name: 'Washed Black' },
      { id: 'slate', hex: '#4B5563', name: 'Mineral Blue' },
    ],
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    description: 'Slouched organic fleece pullover hoodie with no scratchy drawstrings and clean kangaroo pouch.',
    fabric: '100% Organic Loopback Terry (360 GSM).',
    fit: 'Slouchy dropped shoulder volume.',
    rating: 4.8,
    reviewCount: 76,
  },
  {
    id: 'k-05',
    name: 'Structured Denim Overshirt',
    category: 'kids',
    type: 'Outerwear',
    price: '$120.00',
    priceNum: 120,
    image: 'https://images.unsplash.com/photo-1502716119720-b23a93e5fe1b?q=80&w=1000&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1471286174890-9c112ffca56a?q=80&w=1000&auto=format&fit=crop',
    ],
    colors: [
      { id: 'slate', hex: '#4B5563', name: 'Faded Indigo' },
      { id: 'black', hex: '#000000', name: 'Washed Charcoal' },
    ],
    sizes: ['6Y', '8Y', '10Y', '12Y'],
    description: 'Softened 10oz ring-spun denim overshirt featuring metal snap buttons and chest flap pockets.',
    fabric: '100% Washed Cotton Denim.',
    fit: 'Relaxed easy-layering cut.',
    rating: 4.9,
    reviewCount: 39,
  },
  {
    id: 'k-06',
    name: 'Teddy Sherpa Hooded Zip Jacket',
    category: 'kids',
    type: 'Outerwear',
    price: '$130.00',
    priceNum: 130,
    image: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1503919545889-aef636e10ad4?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'chalk', hex: '#E5E7EB', name: 'Teddy Cream' },
      { id: 'charcoal', hex: '#1F2937', name: 'Camel Brown' },
    ],
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    description: 'High-pile plush teddy fleece bonded to jersey lining with smooth nylon zip chest pocket.',
    fabric: '100% Recycled Sherpa Fleece.',
    fit: 'Warm roomy silhouette.',
    rating: 5.0,
    reviewCount: 84,
  },
  {
    id: 'k-07',
    name: 'Relaxed Denim Overall Dungarees',
    category: 'kids',
    type: 'Trousers',
    price: '$110.00',
    priceNum: 110,
    image: 'https://images.unsplash.com/photo-1471286174890-9c112ffca56a?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1502716119720-b23a93e5fe1b?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'slate', hex: '#4B5563', name: 'Vintage Blue' },
      { id: 'black', hex: '#000000', name: 'Washed Black' },
    ],
    sizes: ['4Y', '6Y', '8Y', '10Y'],
    description: 'Classic durable denim overalls with adjustable buckled shoulder straps and functional tool loops.',
    fabric: '100% Cotton Denim (10oz).',
    fit: 'Straight leg relaxed overalls.',
    rating: 4.9,
    reviewCount: 46,
  },
  {
    id: 'k-08',
    name: 'Mini Featherweight Puffer Jacket',
    category: 'kids',
    type: 'Outerwear',
    price: '$160.00',
    priceNum: 160,
    image: 'https://images.unsplash.com/photo-1514090458221-65bb69cf63e6?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?q=80&w=1000&auto=format&fit=crop'],
    status: 'NEW ARRIVAL',
    colors: [
      { id: 'black', hex: '#000000', name: 'Obsidian' },
      { id: 'slate', hex: '#4B5563', name: 'Ice Blue' },
    ],
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    description: 'Ultralight quilted jacket filled with hypoallergenic synthetic insulation, water-resistant and windproof.',
    fabric: '100% Recycled Nylon Shell, Thermolite Insulation.',
    fit: 'Snug hooded winter layer.',
    rating: 5.0,
    reviewCount: 61,
  },
  {
    id: 'k-09',
    name: 'Organic Cotton Long Sleeve Tee',
    category: 'kids',
    type: 'T-Shirts',
    price: '$55.00',
    priceNum: 55,
    image: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1503919545889-aef636e10ad4?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'white', hex: '#FFFFFF', name: 'Chalk White' },
      { id: 'charcoal', hex: '#1F2937', name: 'Heather Smoke' },
    ],
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    description: 'Featherweight breathable combed cotton jersey with soft ribbed wrist cuffs.',
    fabric: '100% Certified Organic Cotton (200 GSM).',
    fit: 'Easy regular everyday fit.',
    rating: 4.8,
    reviewCount: 93,
  },
  {
    id: 'k-10',
    name: 'Fine Rib Knit Wool Beanie',
    category: 'kids',
    type: 'Accessories',
    price: '$45.00',
    priceNum: 45,
    image: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1503919545889-aef636e10ad4?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'black', hex: '#000000', name: 'Black' },
      { id: 'chalk', hex: '#E5E7EB', name: 'Oatmeal' },
      { id: 'charcoal', hex: '#1F2937', name: 'Charcoal' },
    ],
    sizes: ['OS'],
    description: 'Non-itchy fine merino blend beanie with a turn-up cuff and snug shape retention.',
    fabric: '70% Fine Merino Wool, 30% Organic Cotton.',
    fit: 'One size fits all stretch fit.',
    rating: 4.9,
    reviewCount: 115,
  },
  {
    id: 'k-11',
    name: 'Corduroy Elastic Waist Trouser',
    category: 'kids',
    type: 'Trousers',
    price: '$78.00',
    priceNum: 78,
    image: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1471286174890-9c112ffca56a?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'charcoal', hex: '#1F2937', name: 'Warm Tobacco' },
      { id: 'black', hex: '#000000', name: 'Black' },
    ],
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    description: 'Soft 14-wale cotton corduroy with internal elastic waistband and deep slash pockets.',
    fabric: '100% Washed Cotton Corduroy.',
    fit: 'Tapered relaxed trouser.',
    rating: 4.8,
    reviewCount: 49,
  },
  {
    id: 'k-12',
    name: 'Half-Zip Polar Fleece Pullover',
    category: 'kids',
    type: 'Tops',
    price: '$88.00',
    priceNum: 88,
    image: 'https://images.unsplash.com/photo-1514090458221-65bb69cf63e6?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'slate', hex: '#4B5563', name: 'Navy Stone' },
      { id: 'chalk', hex: '#E5E7EB', name: 'Cream' },
    ],
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    description: 'Anti-pill microfleece half-zip with nylon binding on collar and cuffs for everyday exploration.',
    fabric: '100% Recycled Polar Fleece.',
    fit: 'Comfortable athletic layer.',
    rating: 4.9,
    reviewCount: 57,
  },
  {
    id: 'k-13',
    name: 'Brushed Plaid Flannel Shirt',
    category: 'kids',
    type: 'Tops',
    price: '$72.00',
    priceNum: 72,
    image: 'https://images.unsplash.com/photo-1471286174890-9c112ffca56a?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1502716119720-b23a93e5fe1b?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'charcoal', hex: '#1F2937', name: 'Charcoal Plaid' },
      { id: 'slate', hex: '#4B5563', name: 'Blue Shadow' },
    ],
    sizes: ['6Y', '8Y', '10Y', '12Y'],
    description: 'Double-brushed cotton flannel with soft hand feel, durable horn buttons, and twin chest pockets.',
    fabric: '100% Cotton Double-Brushed Flannel.',
    fit: 'Casual overshirt silhouette.',
    rating: 4.7,
    reviewCount: 38,
  },
  {
    id: 'k-14',
    name: 'Cargo Pocket Fleece Sweatshort',
    category: 'kids',
    type: 'Trousers',
    price: '$60.00',
    priceNum: 60,
    image: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'black', hex: '#000000', name: 'Black' },
      { id: 'slate', hex: '#4B5563', name: 'Heather Slate' },
    ],
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    description: 'Loopback terry shorts featuring side cargo bellows pockets and encased soft elastic drawstring.',
    fabric: '100% Organic French Terry (320 GSM).',
    fit: 'Above-the-knee relaxed play fit.',
    rating: 4.8,
    reviewCount: 64,
  },
  {
    id: 'k-15',
    name: 'Waterproof Colorblock Anorak',
    category: 'kids',
    type: 'Outerwear',
    price: '$125.00',
    priceNum: 125,
    image: 'https://images.unsplash.com/photo-1514090458221-65bb69cf63e6?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1502716119720-b23a93e5fe1b?q=80&w=1000&auto=format&fit=crop'],
    status: 'NEW ARRIVAL',
    colors: [
      { id: 'slate', hex: '#4B5563', name: 'Two-Tone Blue' },
      { id: 'black', hex: '#000000', name: 'Black / Sand' },
    ],
    sizes: ['6Y', '8Y', '10Y', '12Y'],
    description: 'Seam-sealed waterproof nylon pullover with front zippered pouch and reflective safety piping.',
    fabric: '2.5-layer Waterproof Ripstop Nylon (10k/10k rating).',
    fit: 'Roomy hooded shell.',
    rating: 4.9,
    reviewCount: 42,
  },
  {
    id: 'k-16',
    name: 'Ribbed Organic Cotton Leggings',
    category: 'kids',
    type: 'Trousers',
    price: '$48.00',
    priceNum: 48,
    image: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1503919545889-aef636e10ad4?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'charcoal', hex: '#1F2937', name: 'Charcoal' },
      { id: 'chalk', hex: '#E5E7EB', name: 'Ecru' },
    ],
    sizes: ['4Y', '6Y', '8Y', '10Y'],
    description: 'Stretchy wide-rib cotton leggings engineered for total movement freedom and non-binding waist.',
    fabric: '96% Organic Cotton, 4% Spandex Rib.',
    fit: 'Snug flexible fit.',
    rating: 4.8,
    reviewCount: 77,
  },
  {
    id: 'k-17',
    name: 'Chunky Cable Knit Jumper',
    category: 'kids',
    type: 'Tops',
    price: '$115.00',
    priceNum: 115,
    image: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'chalk', hex: '#E5E7EB', name: 'Oatmeal Cable' },
      { id: 'slate', hex: '#4B5563', name: 'Indigo Cable' },
    ],
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    description: 'Heritage aran cable knit in ultra-soft wool-cotton yarn that stays soft against sensitive skin.',
    fabric: '60% Fine Merino Wool, 40% Organic Cotton.',
    fit: 'Cozy relaxed fit.',
    rating: 5.0,
    reviewCount: 53,
  },
  {
    id: 'k-18',
    name: 'Padded Quilted Field Vest',
    category: 'kids',
    type: 'Outerwear',
    price: '$95.00',
    priceNum: 95,
    image: 'https://images.unsplash.com/photo-1471286174890-9c112ffca56a?q=80&w=1000&auto=format&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1502716119720-b23a93e5fe1b?q=80&w=1000&auto=format&fit=crop'],
    colors: [
      { id: 'black', hex: '#000000', name: 'Pitch Black' },
      { id: 'charcoal', hex: '#1F2937', name: 'Olive Army' },
    ],
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    description: 'Diamond quilted lightweight vest with snap closure and fleece-lined handwarmer pockets.',
    fabric: 'Water-repellent polyester shell, recycled polyfill.',
    fit: 'Layerable sleeveless vest.',
    rating: 4.8,
    reviewCount: 48,
  },
];
